### ISSUE TITLE
First led on green

### ISSUE THREAD

**Issue by RavvenTw** [chris579/rpi_ws281x.Net#2]
Hi
 
          I drive 60 leds WS2812 using PWM, but all time i have first LED in string green (LED is ok, i try other string).
          Is a simple code that set all leds at same color, is this a know problem?

**Comment by klemmchr** [comment]
Can you show the code you are using?

**Comment by RavvenTw** [comment]
ws281x.Net.Neopixel tiraled = new ws281x.Net.Neopixel(ledCount: 60, pin: 12, channel: 0, stripType: rpi_ws281x.WS2812_STRIP);

tiraled.Begin();

for (var i = 0; i < 60; i++)
         tiraled.SetPixelColor(i, System.Drawing.Color.Red);

tiraled.Show();

very very simple, its my first try

**Comment by klemmchr** [comment]
That's really odd, I never had such a problem. But since this is just a C# wrapper, you may want to head over to [rpi_ws281x](https://github.com/jgarff/rpi_ws281x) and ask your question there, I cannot help you with this one.
